---
- hosts: localhost
  tasks:
  - name: Get mongo
    shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

  - name: Add source
    become: yes
    shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list

  - name: Install mongodb
    become: yes
    apt: pkg=mongodb-org state=latest update_cache=yes

  - name: Start mongo
    become: yes
    shell: "service mongod start"
