---
- hosts: localhost
  tasks:
  - name: Install MySQL
    apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present
    become: yes
  - name: Install pip3
    become: yes
    apt:
      name: python3-pip
      state: present
  - name: Install MySQL Python
    become: yes
    pip:
      name: pymysql
  - name: Create mysql user
    become: yes
    shell: ./user.sh
